### ISSUE TITLE
Why drop apiKeyOrAccessToken?

### ISSUE THREAD

**Issue by yalexyu** [truevault/truevault-js-sdk#13]
I just upgraded from `0.4.0` to `0.5.0` and my authentication scheme no longer works. My current application is not SPA and I rely on this value being available in order to recreate a `TrueVaultClient` when a new page is loaded & when it's necessary.

What's the motivation for dropping `apiKeyOrAccessToken`?

**Comment by yalexyu** [comment]
It seems like I can save the Auth Header and recreate a `TrueVaultClient` that way. It requires some string parsing but that's better than nothing!

**Comment by marshallpierce** [comment]
Can you provide some more context on your use case? I'm not sure I understand why you're reaching into the `TrueVaultClient` and accessing an implementation detail like that.

**Comment by yalexyu** [comment]
Certainly.

As I mentioned before, my application is not SPA. Put differently, after a user logs in with TrueVault, I'll lose reference to the `TrueVaultClient` instance that results from `tvClient = await TrueVaultClient.login(...)` . My best option is to recreate the `TrueVaultClient` with an existing api key or access token via the main constructor (e.g. `new TrueVaultClient(apiKeyOrAccessToken)`)

Originally, in `0.4.0`, it was possible to access `apiKeyOrAccessToken`. So basically, I would do the following:

```
loginButtonEl.addEventListener('click', async e => {
    e.preventDefault();

    try {
        // Authenticate with TrueVault
        tvClient = await TrueVaultClient.login(TV_ACCOUNT_ID, loginDisplayFormEl.email.value, loginDisplayFormEl.password.value);
        const tvUserIdResponse = await tvClient.readCurrentUser();

        // Set hidden tv user id value
        tvUserIdInputEl.value = tvUserIdResponse.id;

        // Set hidden token value
        tvTokenInputEl.value = tvClient.apiKeyOrAccessToken;

        // Submit token and tv user id to our web server
        loginFormEl.submit();

    } catch (e) {
        console.log('Failed to authenticate with TrueVault.');
    }

});
```

Later on in my application, I would recreate the `TrueVaultClient` by making an API call for the saved token. Something like the following:

```
// Load access token
window.addEventListener('load', async () => {
    let authInfo = await $.ajax('/truevault/token');
    window.tvClient = new TrueVaultClient(authInfo.token);
});
```

**Comment by yalexyu** [comment]
With 0.5.0, I've had to make some modifications. 

Login looks like this:
```
loginButtonEl.addEventListener('click', async e => {
    e.preventDefault();

    try {
        tvClient = await TrueVaultClient.login(TV_ACCOUNT_ID, loginDisplayFormEl.email.value, loginDisplayFormEl.password.value);
        const tvUserIdResponse = await tvClient.readCurrentUser();

        // Set hidden tv user id value
        tvUserIdInputEl.value = tvUserIdResponse.id;

        // Set hidden token value
        // E.g. Basic LmVKd2xpekVPd2p...
        tvHttpBasicInputEl.value = tvClient.authHeader.substr(6); // Magic number; Removes "Basic "

        // Form is ready to submit
        loginFormEl.submit();

    } catch (e) {
        console.log('Failed to authenticate with TrueVault.');
    }

});
```

Later on, I'd recreate the `TrueVaultClient` with the following:
```

// Perform above AJAX onWindowLoad
window.addEventListener('load', async () => {
    let authInfo = await getAuthInfo();

    window.tvClient = new TrueVaultClient(authInfo);
});
```

where `authInfo` abides by the new constructor signature: 
```
{
    httpBasic: some-base64-encoded-string-for-auth-header 
}
```

**Comment by marshallpierce** [comment]
I see; thanks for explaining. Would a structure in which a `login`-like call returned the access token directly be a better fit for your needs?

**Comment by yalexyu** [comment]
Yeah, that would be better; I'd rather not have to use a magic number to parse out the `httpHeader` :)
