### ISSUE TITLE
Support username/password login that exposes just the access token, not a configured client

### ISSUE THREAD

**Issue by marshallpierce** [truevault/truevault-js-sdk#15]
This will enable use cases that want to use the an access token in multiple page loads without having to re-login every time.

This addresses #13.

**Comment by marshallpierce** [comment]
This should be fixed by #21. @yalexyu will that approach work for you?

**Comment by yalexyu** [comment]
Yes, I believe so. Thank you!

**Comment by marshallpierce** [comment]
Great, thanks for checking!
